builds:
- main: ./cmd/oras
  binary: ./oras
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  ldflags:
  - -w
  - -X github.com/deislabs/oras/pkg/version.Version={{.Version}}
  - -X github.com/deislabs/oras/pkg/version.BuildMetadata=
  - -X github.com/deislabs/oras/pkg/version.GitCommit={{.FullCommit}}

archive:
  format: tar.gz
  files:
  - LICENSE
