[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/containerd/containerd"
  version = "1.2.6"

[[constraint]]
  name = "github.com/opencontainers/go-digest"
  version = "1.0.0-rc1"

[[constraint]]
  name = "github.com/opencontainers/image-spec"
  version = "1.0.1"

# Test dependency
[[constraint]]
  name = "github.com/docker/distribution"
  version = "v2.7.1"

# These overrides below necessary for using docker/distribution as a test dependency
[[override]]
  name = "rsc.io/letsencrypt"
  branch = "master"
  source = "https://github.com/dmcgowan/letsencrypt.git"
