version: '1.0'
stages:
- test
- build
- release
steps:
  UnitTest:
    title: Run unit tests
    stage: test
    image: golang:1.11
    working_directory: /go/src/github.com/${{CF_REPO_OWNER}}
    commands:
    - ln -s /codefresh/volume/${{CF_REPO_NAME}} ${{CF_REPO_NAME}} && cd ${{CF_REPO_NAME}}
    - make test
  BuildDockerImage:
    title: Build Docker image
    stage: build
    type: build
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
  PushDockerImage:
    title: Push Docker image (latest)
    stage: release
    type: push
    candidate: ${{BuildDockerImage}}
    image_name: orasbot/${{CF_REPO_NAME}}
    registry: dockerhub
