version: '1.0'
stages:
- test
steps:
  UnitTest:
    title: Run unit tests
    stage: test
    image: golang:1.11
    working_directory: /go/src/github.com/${{CF_REPO_OWNER}}
    commands:
    - ln -s /codefresh/volume/${{CF_REPO_NAME}} ${{CF_REPO_NAME}} && cd ${{CF_REPO_NAME}}
    - make test
