name: build

on:
  push:
    branches: main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.15.7'
      - name: run unit tests
        run: make test
      - name: prepare
        id: prepare
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "${VERSION}" == "${BRANCH_NAME}" ]]; then
            VERSION=$(git rev-parse --short HEAD)
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=ref::ghcr.io/${{ github.repository }}:${VERSION}
      - name: docker build
        run: |
          docker build -t ${{ steps.prepare.outputs.ref }} .
      - name: docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: docker push
        run: |
          docker push ${{ steps.prepare.outputs.ref }}
      - name: clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
      - name: upload coverage report
        uses: actions/upload-artifact@master
        with:
          name: oras-coverage-report-${{ github.sha }}
          path: .cover/
        if: always()
